name: cloudrun-deploy
on:
  push:
    branches:
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
    
    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Push to Container Registry and Deploy to GCR
      run:
        bash ./scripts/deploy_to_gcr.sh deploy_to_gcr ${{ secrets.GCP_PROJECT }} ${{ secrets.GCP_SERVICE }} ${{ secrets.GCP_REGION }}
